import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import brandLogo from '../public/assets/brand_logo.png'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="http://fonts.cdnfonts.com/css/lazy-dog" rel="stylesheet"/>
      </Head>

      <main className={styles.main}>
        <div className={styles.brand}>
          <div className={styles.logo}>
            <Image 
              src={brandLogo}
              width={250}
              height={250}
            />
          </div>
          <div>
            <h1>Pelusita</h1>
            <h2>Papelería creativa</h2>
          </div>
        </div>

        <div className={styles.buttons}>
          <a className={styles.pink}>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
